
services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Backend Service
  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/emptycup
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  # Frontend Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongodb_data: